import type { Metadata } from "next";
import { Poppins, Lobster } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  weight: "400",
  variable: "--font-poppins"
});

const lobster = Lobster({
  weight: "400",
  variable: "--font-lobster"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${poppins.variable} ${lobster.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
