import type { Metadata } from "next";
import { Poppins, Lobster } from "next/font/google";
import "./globals.css";

const poppins = Poppins({
  weight: "400",
  variable: "--font-poppins"
});

const lobster = Lobster({
  weight: "400",
  variable: "--font-lobster"
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${poppins.variable} ${lobster.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col relative bg-on-tertiary-container/20 overflow-x-hidden">
  
        <div className="absolute inset-0 z-[-1] pointer-events-none overflow-hidden">
          <div className="absolute top-[-10%] left-[-10%] w-[50%] h-[50%] rounded-full bg-secondary-container/30 blur-3xl"></div>
      
          <div className="absolute top-[40%] left-[50%] w-[60%] h-[60%] rounded-full bg-secondary-container/20 blur-3xl"></div>
        </div>

        <div className="relative z-10 flex flex-col grow">
          {children}
        </div>
  
      </body>
    </html>
  );
}
